<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Schema::disableForeignKeyConstraints();
        DB::table('countries')->truncate();
            $countries = array(
                array("country_code" => "AF", "country_name" => "Afghanistan", "country_phonecode" => "93", "country_currency" => "Afghan afghani", "country_symbol" => "Ø‹", "status" => "1"),
array("country_code" => "AL", "country_name" => "Albania", "country_phonecode" => "355", "country_currency" => "Albanian lek", "country_symbol" => "L", "status" => "1"),
array("country_code" => "DZ", "country_name" => "Algeria", "country_phonecode" => "213", "country_currency" => "Algerian dinar", "country_symbol" => "Ø¯.Ø¬", "status" => "1"),
array("country_code" => "AS", "country_name" => "American Samoa", "country_phonecode" => "1684", "country_currency" => "USD", "country_symbol" => "$", "status" => "1"),
array("country_code" => "AD", "country_name" => "Andorra", "country_phonecode" => "376", "country_currency" => "Euro", "country_symbol" => "â‚¬", "status" => "1"),
array("country_code" => "AO", "country_name" => "Angola", "country_phonecode" => "244", "country_currency" => "Angolan kwanza", "country_symbol" => "Kz", "status" => "1"),
array("country_code" => "AI", "country_name" => "Anguilla", "country_phonecode" => "1264", "country_currency" => "East Caribbean dolla", "country_symbol" => "$", "status" => "1"),
array("country_code" => "AQ", "country_name" => "Antarctica", "country_phonecode" => "0", "country_currency" => "USD", "country_symbol" => "$", "status" => "1"),
array("country_code" => "AG", "country_name" => "Antigua And Barbuda", "country_phonecode" => "1268", "country_currency" => "East Caribbean dolla", "country_symbol" => "$", "status" => "1"),
array("country_code" => "AR", "country_name" => "Argentina", "country_phonecode" => "54", "country_currency" => "Argentine peso", "country_symbol" => "$", "status" => "1"),
array("country_code" => "AM", "country_name" => "Armenia", "country_phonecode" => "374", "country_currency" => "Armenian dram", "country_symbol" => "$", "status" => "1"),
array("country_code" => "AW", "country_name" => "Aruba", "country_phonecode" => "297", "country_currency" => "Aruban florin", "country_symbol" => "Æ’", "status" => "1"),
array("country_code" => "AU", "country_name" => "Australia", "country_phonecode" => "61", "country_currency" => "Australian dollar", "country_symbol" => "$", "status" => "1"),
array("country_code" => "AT", "country_name" => "Austria", "country_phonecode" => "43", "country_currency" => "Euro", "country_symbol" => "â‚¬", "status" => "1"),
array("country_code" => "AZ", "country_name" => "Azerbaijan", "country_phonecode" => "994", "country_currency" => "Azerbaijani manat", "country_symbol" => "$", "status" => "1"),
array("country_code" => "BS", "country_name" => "Bahamas The", "country_phonecode" => "1242", "country_currency" => "USD", "country_symbol" => "$", "status" => "1"),
array("country_code" => "BH", "country_name" => "Bahrain", "country_phonecode" => "973", "country_currency" => "Bahraini dinar", "country_symbol" => ".Ø¯.Ø¨", "status" => "1"),
array("country_code" => "BD", "country_name" => "Bangladesh", "country_phonecode" => "880", "country_currency" => "Bangladeshi taka", "country_symbol" => "à§³", "status" => "1"),
array("country_code" => "BB", "country_name" => "Barbados", "country_phonecode" => "1246", "country_currency" => "Barbadian dollar", "country_symbol" => "$", "status" => "1"),
array("country_code" => "BY", "country_name" => "Belarus", "country_phonecode" => "375", "country_currency" => "Belarusian ruble", "country_symbol" => "Br", "status" => "1"),
array("country_code" => "BE", "country_name" => "Belgium", "country_phonecode" => "32", "country_currency" => "Euro", "country_symbol" => "â‚¬", "status" => "1"),
array("country_code" => "BZ", "country_name" => "Belize", "country_phonecode" => "501", "country_currency" => "Belize dollar", "country_symbol" => "$", "status" => "1"),
array("country_code" => "BJ", "country_name" => "Benin", "country_phonecode" => "229", "country_currency" => "West African CFA fra", "country_symbol" => "Fr", "status" => "1"),
array("country_code" => "BM", "country_name" => "Bermuda", "country_phonecode" => "1441", "country_currency" => "Bermudian dollar", "country_symbol" => "$", "status" => "1"),
array("country_code" => "BT", "country_name" => "Bhutan", "country_phonecode" => "975", "country_currency" => "Bhutanese ngultrum", "country_symbol" => "Nu.", "status" => "1"),
array("country_code" => "BO", "country_name" => "Bolivia", "country_phonecode" => "591", "country_currency" => "Bolivian boliviano", "country_symbol" => "Bs.", "status" => "1"),
array("country_code" => "BA", "country_name" => "Bosnia and Herzegovina", "country_phonecode" => "387", "country_currency" => "Bosnia and Herzegovi", "country_symbol" => "KM or ÐšÐœ", "status" => "1"),
array("country_code" => "BW", "country_name" => "Botswana", "country_phonecode" => "267", "country_currency" => "Botswana pula", "country_symbol" => "P", "status" => "1"),
array("country_code" => "BV", "country_name" => "Bouvet Island", "country_phonecode" => "0", "country_currency" => "USD", "country_symbol" => "$", "status" => "1"),
array("country_code" => "BR", "country_name" => "Brazil", "country_phonecode" => "55", "country_currency" => "Brazilian real", "country_symbol" => "R$", "status" => "1"),
array("country_code" => "IO", "country_name" => "British Indian Ocean Territory", "country_phonecode" => "246", "country_currency" => "United States dollar", "country_symbol" => "$", "status" => "1"),
array("country_code" => "BN", "country_name" => "Brunei", "country_phonecode" => "673", "country_currency" => "Brunei dollar", "country_symbol" => "$", "status" => "1"),
array("country_code" => "BG", "country_name" => "Bulgaria", "country_phonecode" => "359", "country_currency" => "Bulgarian lev", "country_symbol" => "Ð»Ð²", "status" => "1"),
array("country_code" => "BF", "country_name" => "Burkina Faso", "country_phonecode" => "226", "country_currency" => "West African CFA fra", "country_symbol" => "Fr", "status" => "1"),
array("country_code" => "BI", "country_name" => "Burundi", "country_phonecode" => "257", "country_currency" => "Burundian franc", "country_symbol" => "Fr", "status" => "1"),
array("country_code" => "KH", "country_name" => "Cambodia", "country_phonecode" => "855", "country_currency" => "Cambodian riel", "country_symbol" => "áŸ›", "status" => "1"),
array("country_code" => "CM", "country_name" => "Cameroon", "country_phonecode" => "237", "country_currency" => "Central African CFA ", "country_symbol" => "Fr", "status" => "1"),
array("country_code" => "CA", "country_name" => "Canada", "country_phonecode" => "1", "country_currency" => "Canadian dollar", "country_symbol" => "$", "status" => "1"),
array("country_code" => "CV", "country_name" => "Cape Verde", "country_phonecode" => "238", "country_currency" => "Cape Verdean escudo", "country_symbol" => "Esc or $", "status" => "1"),
array("country_code" => "KY", "country_name" => "Cayman Islands", "country_phonecode" => "1345", "country_currency" => "Cayman Islands dolla", "country_symbol" => "$", "status" => "1"),
array("country_code" => "CF", "country_name" => "Central African Republic", "country_phonecode" => "236", "country_currency" => "Central African CFA ", "country_symbol" => "Fr", "status" => "1"),
array("country_code" => "TD", "country_name" => "Chad", "country_phonecode" => "235", "country_currency" => "Central African CFA ", "country_symbol" => "Fr", "status" => "1"),
array("country_code" => "CL", "country_name" => "Chile", "country_phonecode" => "56", "country_currency" => "Chilean peso", "country_symbol" => "$", "status" => "1"),
array("country_code" => "CN", "country_name" => "China", "country_phonecode" => "86", "country_currency" => "Chinese yuan", "country_symbol" => "Â¥ or å…ƒ", "status" => "1"),
array("country_code" => "CX", "country_name" => "Christmas Island", "country_phonecode" => "61", "country_currency" => "USD", "country_symbol" => "$", "status" => "1"),
array("country_code" => "CC", "country_name" => "Cocos (Keeling) Islands", "country_phonecode" => "672", "country_currency" => "Australian dollar", "country_symbol" => "$", "status" => "1"),
array("country_code" => "CO", "country_name" => "Colombia", "country_phonecode" => "57", "country_currency" => "Colombian peso", "country_symbol" => "$", "status" => "1"),
array("country_code" => "KM", "country_name" => "Comoros", "country_phonecode" => "269", "country_currency" => "Comorian franc", "country_symbol" => "Fr", "status" => "1"),
array("country_code" => "CG", "country_name" => "Congo", "country_phonecode" => "242", "country_currency" => "USD", "country_symbol" => "$", "status" => "1"),
array("country_code" => "CD", "country_name" => "Congo The Democratic Republic Of The", "country_phonecode" => "242", "country_currency" => "USD", "country_symbol" => "$", "status" => "1"),
array("country_code" => "CK", "country_name" => "Cook Islands", "country_phonecode" => "682", "country_currency" => "New Zealand dollar", "country_symbol" => "$", "status" => "1"),
array("country_code" => "CR", "country_name" => "Costa Rica", "country_phonecode" => "506", "country_currency" => "Costa Rican colÃ³n", "country_symbol" => "â‚¡", "status" => "1"),
array("country_code" => "CI", "country_name" => "Cote D Ivoire (Ivory Coast)", "country_phonecode" => "225", "country_currency" => "USD", "country_symbol" => "$", "status" => "1"),
array("country_code" => "HR", "country_name" => "Croatia (Hrvatska)", "country_phonecode" => "385", "country_currency" => "USD", "country_symbol" => "$", "status" => "1"),
array("country_code" => "CU", "country_name" => "Cuba", "country_phonecode" => "53", "country_currency" => "Cuban convertible pe", "country_symbol" => "$", "status" => "1"),
array("country_code" => "CY", "country_name" => "Cyprus", "country_phonecode" => "357", "country_currency" => "Euro", "country_symbol" => "â‚¬", "status" => "1"),
array("country_code" => "CZ", "country_name" => "Czech Republic", "country_phonecode" => "420", "country_currency" => "Czech koruna", "country_symbol" => "KÄ", "status" => "1"),
array("country_code" => "DK", "country_name" => "Denmark", "country_phonecode" => "45", "country_currency" => "Danish krone", "country_symbol" => "kr", "status" => "1"),
array("country_code" => "DJ", "country_name" => "Djibouti", "country_phonecode" => "253", "country_currency" => "Djiboutian franc", "country_symbol" => "Fr", "status" => "1"),
array("country_code" => "DM", "country_name" => "Dominica", "country_phonecode" => "1767", "country_currency" => "East Caribbean dolla", "country_symbol" => "$", "status" => "1"),
array("country_code" => "DO", "country_name" => "Dominican Republic", "country_phonecode" => "1809", "country_currency" => "Dominican peso", "country_symbol" => "$", "status" => "1"),
array("country_code" => "TP", "country_name" => "East Timor", "country_phonecode" => "670", "country_currency" => "United States dollar", "country_symbol" => "$", "status" => "1"),
array("country_code" => "EC", "country_name" => "Ecuador", "country_phonecode" => "593", "country_currency" => "United States dollar", "country_symbol" => "$", "status" => "1"),
array("country_code" => "EG", "country_name" => "Egypt", "country_phonecode" => "20", "country_currency" => "Egyptian pound", "country_symbol" => "Â£ or Ø¬.Ù…", "status" => "1"),
array("country_code" => "SV", "country_name" => "El Salvador", "country_phonecode" => "503", "country_currency" => "United States dollar", "country_symbol" => "$", "status" => "1"),
array("country_code" => "GQ", "country_name" => "Equatorial Guinea", "country_phonecode" => "240", "country_currency" => "Central African CFA ", "country_symbol" => "Fr", "status" => "1"),
array("country_code" => "ER", "country_name" => "Eritrea", "country_phonecode" => "291", "country_currency" => "Eritrean nakfa", "country_symbol" => "Nfk", "status" => "1"),
array("country_code" => "EE", "country_name" => "Estonia", "country_phonecode" => "372", "country_currency" => "Euro", "country_symbol" => "â‚¬", "status" => "1"),
array("country_code" => "ET", "country_name" => "Ethiopia", "country_phonecode" => "251", "country_currency" => "Ethiopian birr", "country_symbol" => "Br", "status" => "1"),
array("country_code" => "XA", "country_name" => "External Territories of Australia", "country_phonecode" => "61", "country_currency" => "USD", "country_symbol" => "$", "status" => "1"),
array("country_code" => "FK", "country_name" => "Falkland Islands", "country_phonecode" => "500", "country_currency" => "Falkland Islands pou", "country_symbol" => "Â£", "status" => "1"),
array("country_code" => "FO", "country_name" => "Faroe Islands", "country_phonecode" => "298", "country_currency" => "Danish krone", "country_symbol" => "kr", "status" => "1"),
array("country_code" => "FJ", "country_name" => "Fiji Islands", "country_phonecode" => "679", "country_currency" => "USD", "country_symbol" => "$", "status" => "1"),
array("country_code" => "FI", "country_name" => "Finland", "country_phonecode" => "358", "country_currency" => "Euro", "country_symbol" => "â‚¬", "status" => "1"),
array("country_code" => "FR", "country_name" => "France", "country_phonecode" => "33", "country_currency" => "Euro", "country_symbol" => "€", "status" => "1"),
array("country_code" => "GF", "country_name" => "French Guiana", "country_phonecode" => "594", "country_currency" => "USD", "country_symbol" => "$", "status" => "1"),
array("country_code" => "PF", "country_name" => "French Polynesia", "country_phonecode" => "689", "country_currency" => "CFP franc", "country_symbol" => "Fr", "status" => "1"),
array("country_code" => "TF", "country_name" => "French Southern Territories", "country_phonecode" => "0", "country_currency" => "USD", "country_symbol" => "$", "status" => "1"),
array("country_code" => "GA", "country_name" => "Gabon", "country_phonecode" => "241", "country_currency" => "Central African CFA ", "country_symbol" => "Fr", "status" => "1"),
array("country_code" => "GM", "country_name" => "Gambia The", "country_phonecode" => "220", "country_currency" => "USD", "country_symbol" => "$", "status" => "1"),
array("country_code" => "GE", "country_name" => "Georgia", "country_phonecode" => "995", "country_currency" => "Georgian lari", "country_symbol" => "áƒš", "status" => "1"),
array("country_code" => "DE", "country_name" => "Germany", "country_phonecode" => "49", "country_currency" => "Euro", "country_symbol" => "€", "status" => "1"),
array("country_code" => "GH", "country_name" => "Ghana", "country_phonecode" => "233", "country_currency" => "Ghana cedi", "country_symbol" => "GH₵", "status" => "1"),
array("country_code" => "GI", "country_name" => "Gibraltar", "country_phonecode" => "350", "country_currency" => "Gibraltar pound", "country_symbol" => "Â£", "status" => "1"),
array("country_code" => "GR", "country_name" => "Greece", "country_phonecode" => "30", "country_currency" => "Euro", "country_symbol" => "€", "status" => "1"),
array("country_code" => "GL", "country_name" => "Greenland", "country_phonecode" => "299", "country_currency" => "USD", "country_symbol" => "$", "status" => "1"),
array("country_code" => "GD", "country_name" => "Grenada", "country_phonecode" => "1473", "country_currency" => "East Caribbean dolla", "country_symbol" => "$", "status" => "1"),
array("country_code" => "GP", "country_name" => "Guadeloupe", "country_phonecode" => "590", "country_currency" => "USD", "country_symbol" => "$", "status" => "1"),
array("country_code" => "GU", "country_name" => "Guam", "country_phonecode" => "1671", "country_currency" => "USD", "country_symbol" => "$", "status" => "1"),
array("country_code" => "GT", "country_name" => "Guatemala", "country_phonecode" => "502", "country_currency" => "Guatemalan quetzal", "country_symbol" => "Q", "status" => "1"),
array("country_code" => "XU", "country_name" => "Guernsey and Alderney", "country_phonecode" => "44", "country_currency" => "USD", "country_symbol" => "$", "status" => "1"),
array("country_code" => "GN", "country_name" => "Guinea", "country_phonecode" => "224", "country_currency" => "Guinean franc", "country_symbol" => "Fr", "status" => "1"),
array("country_code" => "GW", "country_name" => "Guinea-Bissau", "country_phonecode" => "245", "country_currency" => "West African CFA fra", "country_symbol" => "Fr", "status" => "1"),
array("country_code" => "GY", "country_name" => "Guyana", "country_phonecode" => "592", "country_currency" => "Guyanese dollar", "country_symbol" => "$", "status" => "1"),
array("country_code" => "HT", "country_name" => "Haiti", "country_phonecode" => "509", "country_currency" => "Haitian gourde", "country_symbol" => "G", "status" => "1"),
array("country_code" => "HM", "country_name" => "Heard and McDonald Islands", "country_phonecode" => "0", "country_currency" => "USD", "country_symbol" => "$", "status" => "1"),
array("country_code" => "HN", "country_name" => "Honduras", "country_phonecode" => "504", "country_currency" => "Honduran lempira", "country_symbol" => "L", "status" => "1"),
array("country_code" => "HK", "country_name" => "Hong Kong S.A.R.", "country_phonecode" => "852", "country_currency" => "USD", "country_symbol" => "$", "status" => "1"),
array("country_code" => "HU", "country_name" => "Hungary", "country_phonecode" => "36", "country_currency" => "Hungarian forint", "country_symbol" => "Ft", "status" => "1"),
array("country_code" => "IS", "country_name" => "Iceland", "country_phonecode" => "354", "country_currency" => "Icelandic krÃ³na", "country_symbol" => "kr", "status" => "1"),
array("country_code" => "IN", "country_name" => "India", "country_phonecode" => "91", "country_currency" => "Indian rupee", "country_symbol" => "₹", "status" => "1"),
array("country_code" => "ID", "country_name" => "Indonesia", "country_phonecode" => "62", "country_currency" => "Indonesian rupiah", "country_symbol" => "Rp", "status" => "1"),
array("country_code" => "IR", "country_name" => "Iran", "country_phonecode" => "98", "country_currency" => "Iranian rial", "country_symbol" => "ï·¼", "status" => "1"),
array("country_code" => "IQ", "country_name" => "Iraq", "country_phonecode" => "964", "country_currency" => "Iraqi dinar", "country_symbol" => "Ø¹.Ø¯", "status" => "1"),
array("country_code" => "IE", "country_name" => "Ireland", "country_phonecode" => "353", "country_currency" => "Euro", "country_symbol" => "â‚¬", "status" => "1"),
array("country_code" => "IL", "country_name" => "Israel", "country_phonecode" => "972", "country_currency" => "Israeli new shekel", "country_symbol" => "â‚ª", "status" => "1"),
array("country_code" => "IT", "country_name" => "Italy", "country_phonecode" => "39", "country_currency" => "Euro", "country_symbol" => "€", "status" => "1"),
array("country_code" => "JM", "country_name" => "Jamaica", "country_phonecode" => "1876", "country_currency" => "Jamaican dollar", "country_symbol" => "$", "status" => "1"),
array("country_code" => "JP", "country_name" => "Japan", "country_phonecode" => "81", "country_currency" => "Japanese yen", "country_symbol" => "Â¥", "status" => "1"),
array("country_code" => "XJ", "country_name" => "Jersey", "country_phonecode" => "44", "country_currency" => "British pound", "country_symbol" => "Â£", "status" => "1"),
array("country_code" => "JO", "country_name" => "Jordan", "country_phonecode" => "962", "country_currency" => "Jordanian dinar", "country_symbol" => "JD", "status" => "1"),
array("country_code" => "KZ", "country_name" => "Kazakhstan", "country_phonecode" => "7", "country_currency" => "Kazakhstani tenge", "country_symbol" => "$", "status" => "1"),
array("country_code" => "KE", "country_name" => "Kenya", "country_phonecode" => "254", "country_currency" => "Kenyan shilling", "country_symbol" => "Sh", "status" => "1"),
array("country_code" => "KI", "country_name" => "Kiribati", "country_phonecode" => "686", "country_currency" => "Australian dollar", "country_symbol" => "$", "status" => "1"),
array("country_code" => "KP", "country_name" => "Korea North", "country_phonecode" => "850", "country_currency" => "USD", "country_symbol" => "$", "status" => "1"),
array("country_code" => "KR", "country_name" => "Korea South", "country_phonecode" => "82", "country_currency" => "USD", "country_symbol" => "$", "status" => "1"),
array("country_code" => "KW", "country_name" => "Kuwait", "country_phonecode" => "965", "country_currency" => "Kuwaiti dinar", "country_symbol" => "Ø¯.Ùƒ", "status" => "1"),
array("country_code" => "KG", "country_name" => "Kyrgyzstan", "country_phonecode" => "996", "country_currency" => "Kyrgyzstani som", "country_symbol" => "Ð»Ð²", "status" => "1"),
array("country_code" => "LA", "country_name" => "Laos", "country_phonecode" => "856", "country_currency" => "Lao kip", "country_symbol" => "â‚­", "status" => "1"),
array("country_code" => "LV", "country_name" => "Latvia", "country_phonecode" => "371", "country_currency" => "Euro", "country_symbol" => "â‚¬", "status" => "1"),
array("country_code" => "LB", "country_name" => "Lebanon", "country_phonecode" => "961", "country_currency" => "Lebanese pound", "country_symbol" => "Ù„.Ù„", "status" => "1"),
array("country_code" => "LS", "country_name" => "Lesotho", "country_phonecode" => "266", "country_currency" => "Lesotho loti", "country_symbol" => "L", "status" => "1"),
array("country_code" => "LR", "country_name" => "Liberia", "country_phonecode" => "231", "country_currency" => "Liberian dollar", "country_symbol" => "$", "status" => "1"),
array("country_code" => "LY", "country_name" => "Libya", "country_phonecode" => "218", "country_currency" => "Libyan dinar", "country_symbol" => "Ù„.Ø¯", "status" => "1"),
array("country_code" => "LI", "country_name" => "Liechtenstein", "country_phonecode" => "423", "country_currency" => "Swiss franc", "country_symbol" => "Fr", "status" => "1"),
array("country_code" => "LT", "country_name" => "Lithuania", "country_phonecode" => "370", "country_currency" => "Euro", "country_symbol" => "â‚¬", "status" => "1"),
array("country_code" => "LU", "country_name" => "Luxembourg", "country_phonecode" => "352", "country_currency" => "Euro", "country_symbol" => "â‚¬", "status" => "1"),
array("country_code" => "MO", "country_name" => "Macau S.A.R.", "country_phonecode" => "853", "country_currency" => "USD", "country_symbol" => "$", "status" => "1"),
array("country_code" => "MK", "country_name" => "Macedonia", "country_phonecode" => "389", "country_currency" => "USD", "country_symbol" => "$", "status" => "1"),
array("country_code" => "MG", "country_name" => "Madagascar", "country_phonecode" => "261", "country_currency" => "Malagasy ariary", "country_symbol" => "Ar", "status" => "1"),
array("country_code" => "MW", "country_name" => "Malawi", "country_phonecode" => "265", "country_currency" => "Malawian kwacha", "country_symbol" => "MK", "status" => "1"),
array("country_code" => "MY", "country_name" => "Malaysia", "country_phonecode" => "60", "country_currency" => "Malaysian ringgit", "country_symbol" => "RM", "status" => "1"),
array("country_code" => "MV", "country_name" => "Maldives", "country_phonecode" => "960", "country_currency" => "Maldivian rufiyaa", "country_symbol" => ".Þƒ", "status" => "1"),
array("country_code" => "ML", "country_name" => "Mali", "country_phonecode" => "223", "country_currency" => "West African CFA fra", "country_symbol" => "Fr", "status" => "1"),
array("country_code" => "MT", "country_name" => "Malta", "country_phonecode" => "356", "country_currency" => "Euro", "country_symbol" => "â‚¬", "status" => "1"),
array("country_code" => "XM", "country_name" => "Man (Isle of)", "country_phonecode" => "44", "country_currency" => "USD", "country_symbol" => "$", "status" => "1"),
array("country_code" => "MH", "country_name" => "Marshall Islands", "country_phonecode" => "692", "country_currency" => "United States dollar", "country_symbol" => "$", "status" => "1"),
array("country_code" => "MQ", "country_name" => "Martinique", "country_phonecode" => "596", "country_currency" => "USD", "country_symbol" => "$", "status" => "1"),
array("country_code" => "MR", "country_name" => "Mauritania", "country_phonecode" => "222", "country_currency" => "Mauritanian ouguiya", "country_symbol" => "UM", "status" => "1"),
array("country_code" => "MU", "country_name" => "Mauritius", "country_phonecode" => "230", "country_currency" => "Mauritian rupee", "country_symbol" => "â‚¨", "status" => "1"),
array("country_code" => "YT", "country_name" => "Mayotte", "country_phonecode" => "269", "country_currency" => "USD", "country_symbol" => "$", "status" => "1"),
array("country_code" => "MX", "country_name" => "Mexico", "country_phonecode" => "52", "country_currency" => "Mexican peso", "country_symbol" => "$", "status" => "1"),
array("country_code" => "FM", "country_name" => "Micronesia", "country_phonecode" => "691", "country_currency" => "Micronesian dollar", "country_symbol" => "$", "status" => "1"),
array("country_code" => "MD", "country_name" => "Moldova", "country_phonecode" => "373", "country_currency" => "Moldovan leu", "country_symbol" => "L", "status" => "1"),
array("country_code" => "MC", "country_name" => "Monaco", "country_phonecode" => "377", "country_currency" => "Euro", "country_symbol" => "â‚¬", "status" => "1"),
array("country_code" => "MN", "country_name" => "Mongolia", "country_phonecode" => "976", "country_currency" => "Mongolian tÃ¶grÃ¶g", "country_symbol" => "â‚®", "status" => "1"),
array("country_code" => "MS", "country_name" => "Montserrat", "country_phonecode" => "1664", "country_currency" => "East Caribbean dolla", "country_symbol" => "$", "status" => "1"),
array("country_code" => "MA", "country_name" => "Morocco", "country_phonecode" => "212", "country_currency" => "Moroccan dirham", "country_symbol" => "Ø¯.Ù….", "status" => "1"),
array("country_code" => "MZ", "country_name" => "Mozambique", "country_phonecode" => "258", "country_currency" => "Mozambican metical", "country_symbol" => "MT", "status" => "1"),
array("country_code" => "MM", "country_name" => "Myanmar", "country_phonecode" => "95", "country_currency" => "Burmese kyat", "country_symbol" => "Ks", "status" => "1"),
array("country_code" => "NA", "country_name" => "Namibia", "country_phonecode" => "264", "country_currency" => "Namibian dollar", "country_symbol" => "$", "status" => "1"),
array("country_code" => "NR", "country_name" => "Nauru", "country_phonecode" => "674", "country_currency" => "Australian dollar", "country_symbol" => "$", "status" => "1"),
array("country_code" => "NP", "country_name" => "Nepal", "country_phonecode" => "977", "country_currency" => "Nepalese rupee", "country_symbol" => "â‚¨", "status" => "1"),
array("country_code" => "AN", "country_name" => "Netherlands Antilles", "country_phonecode" => "599", "country_currency" => "USD", "country_symbol" => "$", "status" => "1"),
array("country_code" => "NL", "country_name" => "Netherlands The", "country_phonecode" => "31", "country_currency" => "USD", "country_symbol" => "$", "status" => "1"),
array("country_code" => "NC", "country_name" => "New Caledonia", "country_phonecode" => "687", "country_currency" => "CFP franc", "country_symbol" => "Fr", "status" => "1"),
array("country_code" => "NZ", "country_name" => "New Zealand", "country_phonecode" => "64", "country_currency" => "New Zealand dollar", "country_symbol" => "$", "status" => "1"),
array("country_code" => "NI", "country_name" => "Nicaragua", "country_phonecode" => "505", "country_currency" => "Nicaraguan cÃ³rdoba", "country_symbol" => "C$", "status" => "1"),
array("country_code" => "NE", "country_name" => "Niger", "country_phonecode" => "227", "country_currency" => "West African CFA fra", "country_symbol" => "Fr", "status" => "1"),
array("country_code" => "NG", "country_name" => "Nigeria", "country_phonecode" => "234", "country_currency" => "Nigerian naira", "country_symbol" => "â‚¦", "status" => "1"),
array("country_code" => "NU", "country_name" => "Niue", "country_phonecode" => "683", "country_currency" => "New Zealand dollar", "country_symbol" => "$", "status" => "1"),
array("country_code" => "NF", "country_name" => "Norfolk Island", "country_phonecode" => "672", "country_currency" => "USD", "country_symbol" => "$", "status" => "1"),
array("country_code" => "MP", "country_name" => "Northern Mariana Islands", "country_phonecode" => "1670", "country_currency" => "USD", "country_symbol" => "$", "status" => "1"),
array("country_code" => "NO", "country_name" => "Norway", "country_phonecode" => "47", "country_currency" => "Norwegian krone", "country_symbol" => "kr", "status" => "1"),
array("country_code" => "OM", "country_name" => "Oman", "country_phonecode" => "968", "country_currency" => "Omani rial", "country_symbol" => "Ø±.Ø¹.", "status" => "1"),
array("country_code" => "PK", "country_name" => "Pakistan", "country_phonecode" => "92", "country_currency" => "Pakistani rupee", "country_symbol" => "â‚¨", "status" => "1"),
array("country_code" => "PW", "country_name" => "Palau", "country_phonecode" => "680", "country_currency" => "Palauan dollar", "country_symbol" => "$", "status" => "1"),
array("country_code" => "PS", "country_name" => "Palestinian Territory Occupied", "country_phonecode" => "970", "country_currency" => "USD", "country_symbol" => "$", "status" => "1"),
array("country_code" => "PA", "country_name" => "Panama", "country_phonecode" => "507", "country_currency" => "Panamanian balboa", "country_symbol" => "B/.", "status" => "1"),
array("country_code" => "PG", "country_name" => "Papua new Guinea", "country_phonecode" => "675", "country_currency" => "Papua New Guinean ki", "country_symbol" => "K", "status" => "1"),
array("country_code" => "PY", "country_name" => "Paraguay", "country_phonecode" => "595", "country_currency" => "Paraguayan guaranÃ­", "country_symbol" => "â‚²", "status" => "1"),
array("country_code" => "PE", "country_name" => "Peru", "country_phonecode" => "51", "country_currency" => "Peruvian nuevo sol", "country_symbol" => "S/.", "status" => "1"),
array("country_code" => "PH", "country_name" => "Philippines", "country_phonecode" => "63", "country_currency" => "Philippine peso", "country_symbol" => "₱", "status" => "1"),
array("country_code" => "PN", "country_name" => "Pitcairn Island", "country_phonecode" => "0", "country_currency" => "USD", "country_symbol" => "$", "status" => "1"),
array("country_code" => "PL", "country_name" => "Poland", "country_phonecode" => "48", "country_currency" => "Polish zÅ‚oty", "country_symbol" => "zÅ‚", "status" => "1"),
array("country_code" => "PT", "country_name" => "Portugal", "country_phonecode" => "351", "country_currency" => "Euro", "country_symbol" => "â‚¬", "status" => "1"),
array("country_code" => "PR", "country_name" => "Puerto Rico", "country_phonecode" => "1787", "country_currency" => "USD", "country_symbol" => "$", "status" => "1"),
array("country_code" => "QA", "country_name" => "Qatar", "country_phonecode" => "974", "country_currency" => "Qatari riyal", "country_symbol" => "Ø±.Ù‚", "status" => "1"),
array("country_code" => "RE", "country_name" => "Reunion", "country_phonecode" => "262", "country_currency" => "USD", "country_symbol" => "$", "status" => "1"),
array("country_code" => "RO", "country_name" => "Romania", "country_phonecode" => "40", "country_currency" => "Romanian leu", "country_symbol" => "lei", "status" => "1"),
array("country_code" => "RU", "country_name" => "Russia", "country_phonecode" => "70", "country_currency" => "Russian ruble", "country_symbol" => "$", "status" => "1"),
array("country_code" => "RW", "country_name" => "Rwanda", "country_phonecode" => "250", "country_currency" => "Rwandan franc", "country_symbol" => "Fr", "status" => "1"),
array("country_code" => "SH", "country_name" => "Saint Helena", "country_phonecode" => "290", "country_currency" => "Saint Helena pound", "country_symbol" => "Â£", "status" => "1"),
array("country_code" => "KN", "country_name" => "Saint Kitts And Nevis", "country_phonecode" => "1869", "country_currency" => "East Caribbean dolla", "country_symbol" => "$", "status" => "1"),
array("country_code" => "LC", "country_name" => "Saint Lucia", "country_phonecode" => "1758", "country_currency" => "East Caribbean dolla", "country_symbol" => "$", "status" => "1"),
array("country_code" => "PM", "country_name" => "Saint Pierre and Miquelon", "country_phonecode" => "508", "country_currency" => "USD", "country_symbol" => "$", "status" => "1"),
array("country_code" => "VC", "country_name" => "Saint Vincent And The Grenadines", "country_phonecode" => "1784", "country_currency" => "East Caribbean dolla", "country_symbol" => "$", "status" => "1"),
array("country_code" => "WS", "country_name" => "Samoa", "country_phonecode" => "684", "country_currency" => "Samoan tÄlÄ", "country_symbol" => "T", "status" => "1"),
array("country_code" => "SM", "country_name" => "San Marino", "country_phonecode" => "378", "country_currency" => "Euro", "country_symbol" => "â‚¬", "status" => "1"),
array("country_code" => "ST", "country_name" => "Sao Tome and Principe", "country_phonecode" => "239", "country_currency" => "SÃ£o TomÃ© and PrÃ­ncip", "country_symbol" => "Db", "status" => "1"),
array("country_code" => "SA", "country_name" => "Saudi Arabia", "country_phonecode" => "966", "country_currency" => "Saudi riyal", "country_symbol" => "Ø±.Ø³", "status" => "1"),
array("country_code" => "SN", "country_name" => "Senegal", "country_phonecode" => "221", "country_currency" => "West African CFA fra", "country_symbol" => "Fr", "status" => "1"),
array("country_code" => "RS", "country_name" => "Serbia", "country_phonecode" => "381", "country_currency" => "Serbian dinar", "country_symbol" => "Ð´Ð¸Ð½. or din.", "status" => "1"),
array("country_code" => "SC", "country_name" => "Seychelles", "country_phonecode" => "248", "country_currency" => "Seychellois rupee", "country_symbol" => "â‚¨", "status" => "1"),
array("country_code" => "SL", "country_name" => "Sierra Leone", "country_phonecode" => "232", "country_currency" => "Sierra Leonean leone", "country_symbol" => "Le", "status" => "1"),
array("country_code" => "SG", "country_name" => "Singapore", "country_phonecode" => "65", "country_currency" => "Brunei dollar", "country_symbol" => "$", "status" => "1"),
array("country_code" => "SK", "country_name" => "Slovakia", "country_phonecode" => "421", "country_currency" => "Euro", "country_symbol" => "â‚¬", "status" => "1"),
array("country_code" => "SI", "country_name" => "Slovenia", "country_phonecode" => "386", "country_currency" => "Euro", "country_symbol" => "â‚¬", "status" => "1"),
array("country_code" => "XG", "country_name" => "Smaller Territories of the UK", "country_phonecode" => "44", "country_currency" => "USD", "country_symbol" => "$", "status" => "1"),
array("country_code" => "SB", "country_name" => "Solomon Islands", "country_phonecode" => "677", "country_currency" => "Solomon Islands doll", "country_symbol" => "$", "status" => "1"),
array("country_code" => "SO", "country_name" => "Somalia", "country_phonecode" => "252", "country_currency" => "Somali shilling", "country_symbol" => "Sh", "status" => "1"),
array("country_code" => "ZA", "country_name" => "South Africa", "country_phonecode" => "27", "country_currency" => "South African rand", "country_symbol" => "R", "status" => "1"),
array("country_code" => "GS", "country_name" => "South Georgia", "country_phonecode" => "0", "country_currency" => "USD", "country_symbol" => "$", "status" => "1"),
array("country_code" => "SS", "country_name" => "South Sudan", "country_phonecode" => "211", "country_currency" => "South Sudanese pound", "country_symbol" => "Â£", "status" => "1"),
array("country_code" => "ES", "country_name" => "Spain", "country_phonecode" => "34", "country_currency" => "Euro", "country_symbol" => "â‚¬", "status" => "1"),
array("country_code" => "LK", "country_name" => "Sri Lanka", "country_phonecode" => "94", "country_currency" => "Sri Lankan rupee", "country_symbol" => "Rs or à¶»à·”", "status" => "1"),
array("country_code" => "SD", "country_name" => "Sudan", "country_phonecode" => "249", "country_currency" => "Sudanese pound", "country_symbol" => "Ø¬.Ø³.", "status" => "1"),
array("country_code" => "SR", "country_name" => "Suriname", "country_phonecode" => "597", "country_currency" => "Surinamese dollar", "country_symbol" => "$", "status" => "1"),
array("country_code" => "SJ", "country_name" => "Svalbard And Jan Mayen Islands", "country_phonecode" => "47", "country_currency" => "USD", "country_symbol" => "$", "status" => "1"),
array("country_code" => "SZ", "country_name" => "Swaziland", "country_phonecode" => "268", "country_currency" => "Swazi lilangeni", "country_symbol" => "L", "status" => "1"),
array("country_code" => "SE", "country_name" => "Sweden", "country_phonecode" => "46", "country_currency" => "Swedish krona", "country_symbol" => "kr", "status" => "1"),
array("country_code" => "CH", "country_name" => "Switzerland", "country_phonecode" => "41", "country_currency" => "Swiss franc", "country_symbol" => "Fr", "status" => "1"),
array("country_code" => "SY", "country_name" => "Syria", "country_phonecode" => "963", "country_currency" => "Syrian pound", "country_symbol" => "Â£ or Ù„.Ø³", "status" => "1"),
array("country_code" => "TW", "country_name" => "Taiwan", "country_phonecode" => "886", "country_currency" => "New Taiwan dollar", "country_symbol" => "$", "status" => "1"),
array("country_code" => "TJ", "country_name" => "Tajikistan", "country_phonecode" => "992", "country_currency" => "Tajikistani somoni", "country_symbol" => "Ð…Ðœ", "status" => "1"),
array("country_code" => "TZ", "country_name" => "Tanzania", "country_phonecode" => "255", "country_currency" => "Tanzanian shilling", "country_symbol" => "Sh", "status" => "1"),
array("country_code" => "TH", "country_name" => "Thailand", "country_phonecode" => "66", "country_currency" => "Thai baht", "country_symbol" => "à¸¿", "status" => "1"),
array("country_code" => "TG", "country_name" => "Togo", "country_phonecode" => "228", "country_currency" => "West African CFA fra", "country_symbol" => "Fr", "status" => "1"),
array("country_code" => "TK", "country_name" => "Tokelau", "country_phonecode" => "690", "country_currency" => "USD", "country_symbol" => "$", "status" => "1"),
array("country_code" => "TO", "country_name" => "Tonga", "country_phonecode" => "676", "country_currency" => "Tongan paÊ»anga", "country_symbol" => "T$", "status" => "1"),
array("country_code" => "TT", "country_name" => "Trinidad And Tobago", "country_phonecode" => "1868", "country_currency" => "Trinidad and Tobago ", "country_symbol" => "$", "status" => "1"),
array("country_code" => "TN", "country_name" => "Tunisia", "country_phonecode" => "216", "country_currency" => "Tunisian dinar", "country_symbol" => "Ø¯.Øª", "status" => "1"),
array("country_code" => "TR", "country_name" => "Turkey", "country_phonecode" => "90", "country_currency" => "Turkish lira", "country_symbol" => "$", "status" => "1"),
array("country_code" => "TM", "country_name" => "Turkmenistan", "country_phonecode" => "7370", "country_currency" => "Turkmenistan manat", "country_symbol" => "m", "status" => "1"),
array("country_code" => "TC", "country_name" => "Turks And Caicos Islands", "country_phonecode" => "1649", "country_currency" => "United States dollar", "country_symbol" => "$", "status" => "1"),
array("country_code" => "TV", "country_name" => "Tuvalu", "country_phonecode" => "688", "country_currency" => "Australian dollar", "country_symbol" => "$", "status" => "1"),
array("country_code" => "UG", "country_name" => "Uganda", "country_phonecode" => "256", "country_currency" => "Ugandan shilling", "country_symbol" => "Sh", "status" => "1"),
array("country_code" => "UA", "country_name" => "Ukraine", "country_phonecode" => "380", "country_currency" => "Ukrainian hryvnia", "country_symbol" => "â‚´", "status" => "1"),
array("country_code" => "AE", "country_name" => "United Arab Emirates", "country_phonecode" => "971", "country_currency" => "United Arab Emirates", "country_symbol" => "Ø¯.Ø¥", "status" => "1"),
array("country_code" => "GB", "country_name" => "United Kingdom", "country_phonecode" => "44", "country_currency" => "British pound", "country_symbol" => "Â£", "status" => "1"),
array("country_code" => "US", "country_name" => "United States", "country_phonecode" => "1", "country_currency" => "United States dollar", "country_symbol" => "$", "status" => "1"),
array("country_code" => "UM", "country_name" => "United States Minor Outlying Islands", "country_phonecode" => "1", "country_currency" => "USD", "country_symbol" => "$", "status" => "1"),
array("country_code" => "UY", "country_name" => "Uruguay", "country_phonecode" => "598", "country_currency" => "Uruguayan peso", "country_symbol" => "$", "status" => "1"),
array("country_code" => "UZ", "country_name" => "Uzbekistan", "country_phonecode" => "998", "country_currency" => "Uzbekistani som", "country_symbol" => "$", "status" => "1"),
array("country_code" => "VU", "country_name" => "Vanuatu", "country_phonecode" => "678", "country_currency" => "Vanuatu vatu", "country_symbol" => "Vt", "status" => "1"),
array("country_code" => "VA", "country_name" => "Vatican City State (Holy See)", "country_phonecode" => "39", "country_currency" => "USD", "country_symbol" => "$", "status" => "1"),
array("country_code" => "VE", "country_name" => "Venezuela", "country_phonecode" => "58", "country_currency" => "Venezuelan bolÃ­var", "country_symbol" => "Bs F", "status" => "1"),
array("country_code" => "VN", "country_name" => "Vietnam", "country_phonecode" => "84", "country_currency" => "Vietnamese Ä‘á»“ng", "country_symbol" => "â‚«", "status" => "1"),
array("country_code" => "VG", "country_name" => "Virgin Islands (British)", "country_phonecode" => "1284", "country_currency" => "USD", "country_symbol" => "$", "status" => "1"),
array("country_code" => "VI", "country_name" => "Virgin Islands (US)", "country_phonecode" => "1340", "country_currency" => "USD", "country_symbol" => "$", "status" => "1"),
array("country_code" => "WF", "country_name" => "Wallis And Futuna Islands", "country_phonecode" => "681", "country_currency" => "USD", "country_symbol" => "$", "status" => "1"),
array("country_code" => "EH", "country_name" => "Western Sahara", "country_phonecode" => "212", "country_currency" => "USD", "country_symbol" => "$", "status" => "1"),
array("country_code" => "YE", "country_name" => "Yemen", "country_phonecode" => "967", "country_currency" => "Yemeni rial", "country_symbol" => "ï·¼", "status" => "1"),
array("country_code" => "YU", "country_name" => "Yugoslavia", "country_phonecode" => "38", "country_currency" => "USD", "country_symbol" => "$", "status" => "1"),
array("country_code" => "ZM", "country_name" => "Zambia", "country_phonecode" => "260", "country_currency" => "Zambian kwacha", "country_symbol" => "ZK", "status" => "1"),
array("country_code" => "ZW", "country_name" => "Zimbabwe", "country_phonecode" => "263", "country_currency" => "Botswana pula", "country_symbol" => "P", "status" => "1")


                );
        DB::table('countries')->insert($countries);
        Schema::enableForeignKeyConstraints();
    }
}